version: "2"
services:
  flask:
    image: taboo:latest
    ports:
      - "5000:5000"
    networks:
      - app
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
    volumes:
      - src:/app/src/
    command:
      python src/app.py
  client:
    image: taboo:latest
    networks:
      - app
    volumes:
      - ./src/client.py:/app/src/client.py
    command:
      bash -c 'sleep 10 && python src/client.py'
  postgres:
    image: postgres:12.2
    networks:
      - app
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
networks:
  app:
    driver: bridge
volumes:
  src:
