version: "3.7"
services:
  flask:
    image: taboo:latest
    ports:
      - "5000:5000"
    networks:
      - app
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
    volumes:
      - ./src/:/app/src/
    entrypoint:
      - /app/src/wait-for-it.sh
      - postgres:5432
      - --
      - flask
      - run
      - --host
      - "0.0.0.0"
      - --port
      - "5000"
  # react:
  #   image: taboo:latest
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app
  #   volumes:
  #     - ./src/:/app/src/
  #   entrypoint:
  #     - npm
  #     - start
  postgres:
    image: postgres:12.2
    networks:
      - app
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
networks:
  app:
    driver: bridge
