version: "2"
services:
  flask:
    image: taboo:latest
    ports:
      - "5000:5000"
    networks:
      - app
    environment:
      - FLASK_APP=src/app.py
    command:
      python src/app.py
  postgres:
    image: postgres:12.2
    networks:
      - app
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
networks:
  app:
    driver: bridge